a = input('digite algo ')
print('o tipo primitivo desse valor é ≈>',type(a))
print('só tem espaço ≈>',str.isspace(a))
print('é numero ≈>',str.isnumeric(a))
print('é letra ≈>',str.isalpha(a))
print('é Alpha numérico ≈>',str.isalnum(a))
print('só tem maiusculas ≈>',str.isupper(a))
print('so tem minusculas ≈>',str.islower(a))
print('esta capitalizada ≈>',str.istitle(a))
